name: 'pull-requests-jscpd'
description: 'Detect copy/paste in PRs'
runs:
  using: 'node20'
  main: 'main.js'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
branding:
  icon: 'search'
  color: 'blue'
